name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: '${{github.workflow}} @ ${{github.head_ref || github.ref_name}}'
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: make lint
      - name: Lint types
        run: make test-types
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
          config: |
            name: Recurly Security Tests
            query-filters:
            paths-ignore:
              - '**/node_modules'
              - '**/*test*'
          queries: + security-and-quality
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: true
        with:
          category: /language:javascript
  test_local:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser:
          - Chrome
          - Firefox
    steps:
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-actions/setup-firefox@v1
      - uses: actions/checkout@v3
      - name: Unit test
        uses: coactions/setup-xvfb@v1
        env:
          BROWSER: ${{matrix.browser}}
          DISPLAY: :99
        with:
          run: make test-unit-ci
  test_remote:
    name: ${{matrix.type}} test (${{matrix.browser}})
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        type:
          - Unit
          - End-to-end
        browser:
          - Chrome-Remote # no unit
          - Firefox-Remote # no unit
          - Safari-Remote
          - Edge-Remote
          - iOS-18-Remote
          - iOS-17-Remote
          - Android-14-Remote
          - Android-13-Remote
          - Android-12-Remote
    steps:
      - uses: ahmadnassri/action-workflow-queue@v1
      - uses: actions/checkout@v3
      - name: Unit test
        if: ${{matrix.type == 'Unit' && matrix.browser != 'Chrome-Remote' && matrix.browser != 'Firefox-Remote'}}
        uses: nick-fields/retry@v2
        env:
          BROWSER: ${{matrix.browser}}
          BROWSER_STACK_USERNAME: ${{secrets.BROWSER_STACK_USERNAME}}
          BROWSER_STACK_ACCESS_KEY: ${{secrets.BROWSER_STACK_ACCESS_KEY}}
        with:
          timeout_minutes: 12
          max_attempts: 2
          command: make test-unit-ci
      - name: End-to-end test
        if: ${{matrix.type == 'End-to-end'}}
        uses: nick-fields/retry@v2
        env:
          BROWSER: ${{matrix.browser}}
          BROWSER_STACK_USERNAME: ${{secrets.BROWSER_STACK_USERNAME}}
          BROWSER_STACK_ACCESS_KEY: ${{secrets.BROWSER_STACK_ACCESS_KEY}}
        with:
          timeout_minutes: 16
          max_attempts: 2
          command: make test-e2e-ci
  integration_test:
    name: Integration test with react-recurly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: recurly/react-recurly
          path: vendor
      - name: react-recurly
        env:
          RECURLY_JS_SHA: ${{github.sha}}
        run: |-
          cd vendor
          make test
  verify:
    name: Verify required checks
    runs-on: ubuntu-latest
    if: ${{always()}}
    needs:
      - lint
      - analyze
      - test_local
      - test_remote
      - integration_test
    steps:
      - name: Check status for pull requests
        if: |-
          ${{
            github.event_name == 'pull_request'
            && needs.lint.result != 'success'
            && needs.analyze.result != 'success'
            && needs.test_local.result != 'success'
            && needs.test_remote.result != 'success'
            && needs.integration_test.result != 'success'
          }}
        run: exit 1
  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    needs:
      - lint
      - analyze
      - test_local
      - test_remote
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v1
      - name: Build
        run: make build
      - name: Report coverage
        uses: coactions/setup-xvfb@v1
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
          DISPLAY: :99
        with:
          run: make test-unit-cov-ci
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GCR_QA_PUBLIC_DEVOPS_SA}}
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: build
          destination: ${{secrets.ARTIFACT_BUCKET_NAME}}/recurly-js/${{github.sha}}/
          parent: false
          process_gcloudignore: false
      - name: Upload to Google Cloud Storage for pull requests
        if: ${{github.event_name == 'pull_request'}}
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: build
          destination: ${{secrets.ARTIFACT_BUCKET_NAME}}/recurly-js/pull-request--${{github.event.number}}/
          parent: false
          process_gcloudignore: false
      - name: Summarize
        run: |
          echo "### Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{github.sha}}\`" >> $GITHUB_STEP_SUMMARY
          $(${{github.event_name == 'pull_request'}} = true) && echo "- \`pull-request--${{github.event.number}}\`" >> $GITHUB_STEP_SUMMARY
